---
---

<link rel="stylesheet" href="styles.css" type="text/css">




## Pig Latin – Relational Operations

### Loading and Storing
- LOAD	To Load the data from the file system (local/HDFS) into a relation.
- STORE	To save a relation to the file system (local/HDFS).

### Filtering
- FILTER	To remove unwanted rows from a relation.
- DISTINCT	To remove duplicate rows from a relation.
- FOREACH, GENERATE	To generate data transformations based on columns of data.
- STREAM	To transform a relation using an external program.

### Grouping and Joining
- JOIN	To join two or more relations.
- COGROUP	To group the data in two or more relations.
- GROUP	To group the data in a single relation.
- CROSS	To create the cross product of two or more relations.

### Sorting
- ORDER	To arrange a relation in a sorted order based on one or more fields (ascending or descending).
- LIMIT	To get a limited number of tuples from a relation.

### Combining and Splitting
- UNION	To combine two or more relations into a single relation.
- SPLIT	To split a single relation into two or more relations.

### Diagnostic Operators
- DUMP	To print the contents of a relation on the console.
- DESCRIBE	To describe the schema of a relation.
- EXPLAIN	To view the logical, physical, or MapReduce execution plans to compute a relation.
- ILLUSTRATE	To view the step-by-step execution of a series of statements.

